# /health-finder/backend/docker-compose.yml

version: '3.8'

services:
  # Twoja aplikacja NestJS
  api:
    build: .              # Kropka oznacza: "szukaj Dockerfile w tym samym folderze co ten plik"
    container_name: gym-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      # Dane do połączenia z bazą WEWNĄTRZ sieci Dockera
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - postgres
    networks:
      - gym-network

  # Baza danych PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: gym-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gym-network

volumes:
  postgres_data:

networks:
  gym-network: